### ISSUE TITLE
Decrease default query timeout

### ISSUE THREAD

**Issue by agusaldasoro** [decentraland/catalyst#1040]
It currently is 5 minutes, we should decrease it. And also, modify all stream queries to the database to use a different time out, as they may take much more time.

**Comment by agusaldasoro** [comment]
Also, the following error is frequent:

```
🔥 Error in database connection with state connected:
error: terminating connection due to idle-in-transaction timeout
    at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 122,
  severity: 'FATAL',
  code: '25P03',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'postgres.c',
  line: '3146',
  routine: 'ProcessInterrupts'
}
🔥 Error in database connection with state connected:
Error: Connection terminated unexpectedly
    at Connection.<anonymous> (/app/node_modules/pg-promise/node_modules/pg/lib/client.js:132:73)
    at Object.onceWrapper (node:events:641:28)
    at Connection.emit (node:events:527:28)
    at Socket.<anonymous> (/app/node_modules/pg-promise/node_modules/pg/lib/connection.js:107:12)
    at Socket.emit (node:events:539:35)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**Comment by menduz** [comment]
Can the transaction being executed appear in the log?

**Comment by marianogoldman** [comment]
@menduz 
There's code already [handling this](https://github.com/decentraland/catalyst/blob/main/content/src/repository/Database.ts#L63-L65).
I guess the issue here is debug level. Should we increase it to `warn` or `info`? Not sure what min level is actually being used in prod.
