### ISSUE TITLE
Cannot start a catalyst with `DISABLE_SYNCHRONIZATION` on localhost

### ISSUE THREAD

**Issue by guidota** [decentraland/catalyst#950]
## Description

When disabling synchronization, application won't start due an error on the identity process.

```
2022-03-02T16:40:34.747Z [ERROR] (CatalystIdentityProvider): Failed to detect my own identity
FetchError: request to http://localhost/content/challenge failed, reason: connect ECONNREFUSED 127.0.0.1:80    "Failed to detect my own identity \nFetchError: request to http://localhost/content/challenge failed, reason: connect ECONNREFUSED 127.0.0.1:80"
Trace
    at Object.error (/app/node_modules/@well-known-components/logger/dist/helpers.js:35:33)
    at determineCatalystIdentity (/app/content/logic/cluster-helpers.js:55:16)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ContentCluster.start (/app/content/service/synchronization/ContentCluster.js:34:9)
<<< Error initializing component: "contentCluster". Error will appear in the next line >>>
FetchError: request to http://localhost/content/challenge failed, reason: connect ECONNREFUSED 127.0.0.1:80
<<< Error initializing components. Stopping components and closing application. >>>

/app/node_modules/node-fetch/lib/index.js:1491
                        reject(new FetchError(`request to ${request.url} failed, reason: ${err.message}`, 'system', err));
                               ^
FetchError: request to http://localhost/content/challenge failed, reason: connect ECONNREFUSED 127.0.0.1:80
    at ClientRequest.<anonymous> (/app/node_modules/node-fetch/lib/index.js:1491:11)
    at ClientRequest.emit (node:events:520:28)
    at Socket.socketErrorListener (node:_http_client:442:9)
    at Socket.emit (node:events:520:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  type: 'system',
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED'
}

```

**Comment by guidota** [comment]
Actually is not related to `DISABLE_SYNCHRONIZATION` config, just using `http://localhost` as `CATALYST_URL`
